app = 'wunschliste'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  FLATNOTES_AUTH_TYPE = 'password'
  FLATNOTES_SESSION_EXPIRY_DAYS = '1'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'
  snapshot_retention = 14

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.ready]
    port = 8080
    type = 'http'
    interval = '5s'
    timeout = '1s'
    grace_period = '1s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
